trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: UnitTest
    condition: |
      and(
        not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')),
        or(
          eq(variables['Build.Reason'], 'PullRequest'),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )
      )
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.38.0-x86_64-pc-windows-msvc'
      - script: make test
        displayName: Run unit tests
        env:
          CI: true

  - job: Package
    timeoutInMinutes: 0
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.38.0-x86_64-pc-windows-msvc'
      - script: make prod
        displayName: Build
      - powershell: |
          mkdir ckb-cli_$(Build.SourceBranchName)_x86_64-pc-windows-msvc
          cp -r target/release/ckb-cli.exe,README.md,CHANGELOG.md,COPYING ckb-cli_$(Build.SourceBranchName)_x86_64-pc-windows-msvc
        displayName: Prepare archive
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'ckb-cli_$(Build.SourceBranchName)_x86_64-pc-windows-msvc'
          archiveFile: '$(Build.ArtifactStagingDirectory)/ckb-cli_$(Build.SourceBranchName)_x86_64-pc-windows-msvc.zip'
      - script: |
          scoop bucket add extras
          scoop install gpg4win
        displayName: Install GPG4Win
      - task: DownloadSecureFile@1
        inputs:
          secureFile: azure-secret.asc
      - script: |
          set PATH=%PATH%;%ProgramFiles(x86)%/GnuPG/bin
          gpg --import %DOWNLOADSECUREFILE_SECUREFILEPATH%
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%ProgramFiles(x86)%/GnuPG/bin"
        displayName: Setup GPG
      - script: |
          gpg -u "Nervos Azure Builder <bot@nervos.org>" -ab "$(Build.ArtifactStagingDirectory)/ckb-cli_$(Build.SourceBranchName)_x86_64-pc-windows-msvc.zip"
        displayName: Sign Archive
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: nervos-bot
          repositoryName: nervosnetwork/ckb-cli
          action: edit
          tag: $(Build.SourceBranchName)
          assets: |
            $(Build.ArtifactStagingDirectory)/*.zip
            $(Build.ArtifactStagingDirectory)/*.asc
          assetUploadMode: replace
          isPreRelease: true
          addChangeLog: false
